site_name: Yi Zhou's Homepage
nav:
 - HomePage:   
    - English: index_en.md    
    - 中文: index.md
 - Research: 
    - publication: research/publication.md
    - Relaxed Clique: research/relaxcliquesolver/relaxedclique.md    
    - submodular optimization solver: research/submodular/submax.md
 - Teaching: 
    - 最优化算法: course/optimization.md
 - My Group: 
    - Introduction: aegroup/aegroup.md    
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
 #   - header.autohide
markdown_extensions:
  - meta
  - attr_list
  - pymdownx.emoji:
     emoji_index: !!python/name:material.extensions.emoji.twemoji
     emoji_generator: !!python/name:material.extensions.emoji.to_svg



  